### ISSUE TITLE
Does this still work? 

### ISSUE THREAD

**Issue by coolcourd** [shabbybastard/zpanel-raspbian-install#1]
I tried installing but see this
E: Package 'libapache2-mod-php5' has no installation candidate
E: Package 'php5-common' has no installation candidate
E: Package 'php5-cli' has no installation candidate
E: Package 'php5-mysql' has no installation candidate
E: Package 'php5-gd' has no installation candidate
E: Package 'php5-mcrypt' has no installation candidate
E: Package 'php5-curl' has no installation candidate
E: Package 'php5-imap' has no installation candidate
E: Package 'php5-xmlrpc' has no installation candidate
E: Package 'php5-xsl' has no installation candidate
it then gets hung asking for my root mysql password. I had mysql installed previously so i uninstalled it and tried again but diddn't get any farther.

**Comment by shabbybastard** [comment]
Nope, it haven't maintained for 3 years.
